import { useState, useEffect } from 'react';
import { useToast } from '@/hooks/use-toast';

interface LanguageConfig {
  code: string;
  name: string;
  flag: string;
}

export const languages: LanguageConfig[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
];

// Enhanced translation dictionary with comprehensive coverage for all languages
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'Home': 'Home',
    'Marketplace': 'Marketplace',
    'Sell Items': 'Sell Items',
    'Crypto Exchange': 'Crypto Exchange',
    'Messages': 'Messages',
    'Forum': 'Forum',
    'Settings': 'Settings',
    'Profile': 'Profile',
    'Wallet': 'Wallet',
    'Friends': 'Friends',
    
    // Profile Hub
    'Profile Hub': 'Profile Hub',
    'Loading profile...': 'Loading profile...',
    'Edit': 'Edit',
    'Cancel': 'Cancel',
    'Save': 'Save',
    'Username': 'Username',
    'Bio': 'Bio',
    'Your username': 'Your username',
    'Add your bio': 'Add your bio',
    'Tell us about yourself': 'Tell us about yourself',
    'Member since': 'Member since',
    'Crypto Wallet': 'Crypto Wallet',
    '0x... your wallet address': '0x... your wallet address',
    'Account Settings': 'Account Settings',
    'Account Email': 'Account Email',
    'Loading...': 'Loading...',
    'Private - never shown to other users': 'Private - never shown to other users',
    'Email Notifications': 'Email Notifications',
    'Updates about transactions and messages': 'Updates about transactions and messages',
    'Two-Factor Authentication': 'Two-Factor Authentication',
    'Extra security for your account': 'Extra security for your account',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': 'The premier digital marketplace for gift cards, game accounts, and premium subscriptions',
    'Browse Marketplace': 'Browse Marketplace',
    'Start Selling': 'Start Selling',
    'Search digital items...': 'Search digital items...',
    'Why Choose SKID HAVEN?': 'Why Choose SKID HAVEN?',
    'Secure Trading': 'Secure Trading',
    'Protected transactions': 'Protected transactions',
    'Instant Delivery': 'Instant Delivery',
    'Digital items in minutes': 'Digital items in minutes',
    'Trusted Community': 'Trusted Community',
    'Verified traders': 'Verified traders',
    'Privacy First': 'Privacy First',
    'Encrypted & secure': 'Encrypted & secure',
    'Multiple Payments': 'Multiple Payments',
    'Crypto, PayPal & more': 'Crypto, PayPal & more',
    'Reputation System': 'Reputation System',
    'Verified sellers': 'Verified sellers',
    'Popular Categories': 'Popular Categories',
    'Gift Cards': 'Gift Cards',
    'Game Accounts': 'Game Accounts',
    'Premium Subs': 'Premium Subs',
    'Digital Content': 'Digital Content',
    '0 items': '0 items',
    'Ready to Start Trading?': 'Ready to Start Trading?',
    'Join our community of digital traders': 'Join our community of digital traders',
    'Join Community': 'Join Community',
    'Start Chatting': 'Start Chatting',
    'Active Users': 'Active Users',
    'Items Sold': 'Items Sold',
    'Transactions': 'Transactions',
    'Success Rate': 'Success Rate',
    
    // Auth
    'Login': 'Login',
    'Sign Up': 'Sign Up',
    'Sign Out': 'Sign Out',
  },
  es: {
    // Navigation
    'Home': 'Inicio',
    'Marketplace': 'Mercado',
    'Sell Items': 'Vender',
    'Crypto Exchange': 'Intercambio Crypto',
    'Messages': 'Mensajes',
    'Forum': 'Foro',
    'Settings': 'Configuración',
    'Profile': 'Perfil',
    'Wallet': 'Billetera',
    'Friends': 'Amigos',
    
    // Profile Hub
    'Profile Hub': 'Centro de Perfil',
    'Loading profile...': 'Cargando perfil...',
    'Edit': 'Editar',
    'Cancel': 'Cancelar',
    'Save': 'Guardar',
    'Username': 'Nombre de usuario',
    'Bio': 'Biografía',
    'Your username': 'Tu nombre de usuario',
    'Add your bio': 'Añade tu biografía',
    'Tell us about yourself': 'Cuéntanos sobre ti',
    'Member since': 'Miembro desde',
    'Crypto Wallet': 'Billetera Crypto',
    '0x... your wallet address': '0x... tu dirección de billetera',
    'Account Settings': 'Configuración de Cuenta',
    'Account Email': 'Email de Cuenta',
    'Loading...': 'Cargando...',
    'Private - never shown to other users': 'Privado - nunca mostrado a otros usuarios',
    'Email Notifications': 'Notificaciones por Email',
    'Updates about transactions and messages': 'Actualizaciones sobre transacciones y mensajes',
    'Two-Factor Authentication': 'Autenticación de Dos Factores',
    'Extra security for your account': 'Seguridad adicional para tu cuenta',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': 'El mercado digital principal para tarjetas de regalo, cuentas de juego y suscripciones premium',
    'Browse Marketplace': 'Explorar Mercado',
    'Start Selling': 'Comenzar a Vender',
    'Search digital items...': 'Buscar artículos digitales...',
    'Why Choose SKID HAVEN?': '¿Por qué elegir SKID HAVEN?',
    'Secure Trading': 'Comercio Seguro',
    'Protected transactions': 'Transacciones protegidas',
    'Instant Delivery': 'Entrega Instantánea',
    'Digital items in minutes': 'Artículos digitales en minutos',
    'Trusted Community': 'Comunidad Confiable',
    'Verified traders': 'Comerciantes verificados',
    'Privacy First': 'Privacidad Primero',
    'Encrypted & secure': 'Encriptado y seguro',
    'Multiple Payments': 'Múltiples Pagos',
    'Crypto, PayPal & more': 'Crypto, PayPal y más',
    'Reputation System': 'Sistema de Reputación',
    'Verified sellers': 'Vendedores verificados',
    'Popular Categories': 'Categorías Populares',
    'Gift Cards': 'Tarjetas de Regalo',
    'Game Accounts': 'Cuentas de Juego',
    'Premium Subs': 'Suscripciones Premium',
    'Digital Content': 'Contenido Digital',
    '0 items': '0 artículos',
    'Ready to Start Trading?': '¿Listo para Comenzar a Comerciar?',
    'Join our community of digital traders': 'Únete a nuestra comunidad de comerciantes digitales',
    'Join Community': 'Unirse a la Comunidad',
    'Start Chatting': 'Comenzar a Chatear',
    'Active Users': 'Usuarios Activos',
    'Items Sold': 'Artículos Vendidos',
    'Transactions': 'Transacciones',
    'Success Rate': 'Tasa de Éxito',
    
    // Auth
    'Login': 'Iniciar Sesión',
    'Sign Up': 'Registrarse',
    'Sign Out': 'Cerrar Sesión',
  },
  fr: {
    // Navigation
    'Home': 'Accueil',
    'Marketplace': 'Marché',
    'Sell Items': 'Vendre',
    'Crypto Exchange': 'Échange Crypto',
    'Messages': 'Messages',
    'Forum': 'Forum',
    'Settings': 'Paramètres',
    'Profile': 'Profil',
    'Wallet': 'Portefeuille',
    'Friends': 'Amis',
    
    // Profile Hub
    'Profile Hub': 'Centre de Profil',
    'Loading profile...': 'Chargement du profil...',
    'Edit': 'Modifier',
    'Cancel': 'Annuler',
    'Save': 'Sauvegarder',
    'Username': "Nom d'utilisateur",
    'Bio': 'Biographie',
    'Your username': "Votre nom d'utilisateur",
    'Add your bio': 'Ajoutez votre biographie',
    'Tell us about yourself': 'Parlez-nous de vous',
    'Member since': 'Membre depuis',
    'Crypto Wallet': 'Portefeuille Crypto',
    '0x... your wallet address': '0x... votre adresse de portefeuille',
    'Account Settings': 'Paramètres du Compte',
    'Account Email': 'Email du Compte',
    'Loading...': 'Chargement...',
    'Private - never shown to other users': 'Privé - jamais montré aux autres utilisateurs',
    'Email Notifications': 'Notifications par Email',
    'Updates about transactions and messages': 'Mises à jour sur les transactions et messages',
    'Two-Factor Authentication': 'Authentification à Deux Facteurs',
    'Extra security for your account': 'Sécurité supplémentaire pour votre compte',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': 'Le marché numérique principal pour les cartes-cadeaux, comptes de jeu et abonnements premium',
    'Browse Marketplace': 'Parcourir le Marché',
    'Start Selling': 'Commencer à Vendre',
    'Search digital items...': 'Rechercher des articles numériques...',
    'Why Choose SKID HAVEN?': 'Pourquoi choisir SKID HAVEN?',
    'Secure Trading': 'Commerce Sécurisé',
    'Protected transactions': 'Transactions protégées',
    'Instant Delivery': 'Livraison Instantanée',
    'Digital items in minutes': 'Articles numériques en minutes',
    'Trusted Community': 'Communauté de Confiance',
    'Verified traders': 'Commerçants vérifiés',
    'Privacy First': 'Confidentialité d\'abord',
    'Encrypted & secure': 'Chiffré et sécurisé',
    'Multiple Payments': 'Paiements Multiples',
    'Crypto, PayPal & more': 'Crypto, PayPal et plus',
    'Reputation System': 'Système de Réputation',
    'Verified sellers': 'Vendeurs vérifiés',
    'Popular Categories': 'Catégories Populaires',
    'Gift Cards': 'Cartes-Cadeaux',
    'Game Accounts': 'Comptes de Jeu',
    'Premium Subs': 'Abonnements Premium',
    'Digital Content': 'Contenu Numérique',
    '0 items': '0 articles',
    'Ready to Start Trading?': 'Prêt à Commencer le Commerce?',
    'Join our community of digital traders': 'Rejoignez notre communauté de commerçants numériques',
    'Join Community': 'Rejoindre la Communauté',
    'Start Chatting': 'Commencer à Discuter',
    'Active Users': 'Utilisateurs Actifs',
    'Items Sold': 'Articles Vendus',
    'Transactions': 'Transactions',
    'Success Rate': 'Taux de Réussite',
    
    // Auth
    'Login': 'Connexion',
    'Sign Up': 'S\'inscrire',
    'Sign Out': 'Déconnexion',
  },
  de: {
    // Navigation
    'Home': 'Startseite',
    'Marketplace': 'Marktplatz',
    'Sell Items': 'Verkaufen',
    'Crypto Exchange': 'Krypto-Börse',
    'Messages': 'Nachrichten',
    'Forum': 'Forum',
    'Settings': 'Einstellungen',
    'Profile': 'Profil',
    'Wallet': 'Geldbörse',
    'Friends': 'Freunde',
    
    // Profile Hub
    'Profile Hub': 'Profil-Center',
    'Loading profile...': 'Profil wird geladen...',
    'Edit': 'Bearbeiten',
    'Cancel': 'Abbrechen',
    'Save': 'Speichern',
    'Username': 'Benutzername',
    'Bio': 'Biographie',
    'Your username': 'Ihr Benutzername',
    'Add your bio': 'Fügen Sie Ihre Biographie hinzu',
    'Tell us about yourself': 'Erzählen Sie uns von sich',
    'Member since': 'Mitglied seit',
    'Crypto Wallet': 'Krypto-Geldbörse',
    '0x... Ihre wallet address': '0x... Ihre Wallet-Adresse',
    'Account Settings': 'Kontoeinstellungen',
    'Account Email': 'Konto-E-Mail',
    'Loading...': 'Wird geladen...',
    'Private - never shown to other users': 'Privat - wird anderen Benutzern nie gezeigt',
    'Email Notifications': 'E-Mail-Benachrichtigungen',
    'Updates about transactions and messages': 'Updates über Transaktionen und Nachrichten',
    'Two-Factor Authentication': 'Zwei-Faktor-Authentifizierung',
    'Extra security for your account': 'Zusätzliche Sicherheit für Ihr Konto',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': 'Der führende digitale Marktplatz für Geschenkkarten, Spielkonten und Premium-Abonnements',
    'Browse Marketplace': 'Marktplatz durchsuchen',
    'Start Selling': 'Verkauf beginnen',
    'Search digital items...': 'Digitale Artikel suchen...',
    'Why Choose SKID HAVEN?': 'Warum SKID HAVEN wählen?',
    'Secure Trading': 'Sicherer Handel',
    'Protected transactions': 'Geschützte Transaktionen',
    'Instant Delivery': 'Sofortige Lieferung',
    'Digital items in minutes': 'Digitale Artikel in Minuten',
    'Trusted Community': 'Vertrauenswürdige Gemeinschaft',
    'Verified traders': 'Verifizierte Händler',
    'Privacy First': 'Datenschutz zuerst',
    'Encrypted & secure': 'Verschlüsselt und sicher',
    'Multiple Payments': 'Mehrere Zahlungen',
    'Crypto, PayPal & more': 'Krypto, PayPal und mehr',
    'Reputation System': 'Bewertungssystem',
    'Verified sellers': 'Verifizierte Verkäufer',
    'Popular Categories': 'Beliebte Kategorien',
    'Gift Cards': 'Geschenkkarten',
    'Game Accounts': 'Spielkonten',
    'Premium Subs': 'Premium-Abos',
    'Digital Content': 'Digitaler Inhalt',
    '0 items': '0 Artikel',
    'Ready to Start Trading?': 'Bereit zum Handeln?',
    'Join our community of digital traders': 'Treten Sie unserer Gemeinschaft digitaler Händler bei',
    'Join Community': 'Gemeinschaft beitreten',
    'Start Chatting': 'Chat beginnen',
    'Active Users': 'Aktive Benutzer',
    'Items Sold': 'Verkaufte Artikel',
    'Transactions': 'Transaktionen',
    'Success Rate': 'Erfolgsrate',
    
    // Auth
    'Login': 'Anmelden',
    'Sign Up': 'Registrieren',
    'Sign Out': 'Abmelden',
  },
  pt: {
    // Navigation
    'Home': 'Início',
    'Marketplace': 'Mercado',
    'Sell Items': 'Vender',
    'Crypto Exchange': 'Câmbio Crypto',
    'Messages': 'Mensagens',
    'Forum': 'Fórum',
    'Settings': 'Configurações',
    'Profile': 'Perfil',
    'Wallet': 'Carteira',
    'Friends': 'Amigos',
    
    // Profile Hub
    'Profile Hub': 'Centro de Perfil',
    'Loading profile...': 'Carregando perfil...',
    'Edit': 'Editar',
    'Cancel': 'Cancelar',
    'Save': 'Salvar',
    'Username': 'Nome de usuário',
    'Bio': 'Biografia',
    'Your username': 'Seu nome de usuário',
    'Add your bio': 'Adicione sua biografia',
    'Tell us about yourself': 'Conte-nos sobre você',
    'Member since': 'Membro desde',
    'Crypto Wallet': 'Carteira Crypto',
    '0x... your wallet address': '0x... seu endereço de carteira',
    'Account Settings': 'Configurações da Conta',
    'Account Email': 'Email da Conta',
    'Loading...': 'Carregando...',
    'Private - never shown to other users': 'Privado - nunca mostrado a outros usuários',
    'Email Notifications': 'Notificações por Email',
    'Updates about transactions and messages': 'Atualizações sobre transações e mensagens',
    'Two-Factor Authentication': 'Autenticação de Dois Fatores',
    'Extra security for your account': 'Segurança extra para sua conta',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': 'O principal mercado digital para cartões-presente, contas de jogos e assinaturas premium',
    'Browse Marketplace': 'Navegar no Mercado',
    'Start Selling': 'Começar a Vender',
    'Search digital items...': 'Buscar itens digitais...',
    'Why Choose SKID HAVEN?': 'Por que escolher SKID HAVEN?',
    'Secure Trading': 'Comércio Seguro',
    'Protected transactions': 'Transações protegidas',
    'Instant Delivery': 'Entrega Instantânea',
    'Digital items in minutes': 'Itens digitais em minutos',
    'Trusted Community': 'Comunidade Confiável',
    'Verified traders': 'Comerciantes verificados',
    'Privacy First': 'Privacidade em Primeiro',
    'Encrypted & secure': 'Criptografado e seguro',
    'Multiple Payments': 'Múltiplos Pagamentos',
    'Crypto, PayPal & more': 'Crypto, PayPal e mais',
    'Reputation System': 'Sistema de Reputação',
    'Verified sellers': 'Vendedores verificados',
    'Popular Categories': 'Categorias Populares',
    'Gift Cards': 'Cartões-Presente',
    'Game Accounts': 'Contas de Jogos',
    'Premium Subs': 'Assinaturas Premium',
    'Digital Content': 'Conteúdo Digital',
    '0 items': '0 itens',
    'Ready to Start Trading?': 'Pronto para Começar a Negociar?',
    'Join our community of digital traders': 'Junte-se à nossa comunidade de comerciantes digitais',
    'Join Community': 'Juntar-se à Comunidade',
    'Start Chatting': 'Começar a Conversar',
    'Active Users': 'Usuários Ativos',
    'Items Sold': 'Itens Vendidos',
    'Transactions': 'Transações',
    'Success Rate': 'Taxa de Sucesso',
    
    // Auth
    'Login': 'Entrar',
    'Sign Up': 'Registrar',
    'Sign Out': 'Sair',
  },
  ru: {
    // Navigation
    'Home': 'Главная',
    'Marketplace': 'Маркетплейс',
    'Sell Items': 'Продавать',
    'Crypto Exchange': 'Крипто Обмен',
    'Messages': 'Сообщения',
    'Forum': 'Форум',
    'Settings': 'Настройки',
    'Profile': 'Профиль',
    'Wallet': 'Кошелек',
    'Friends': 'Друзья',
    
    // Profile Hub
    'Profile Hub': 'Центр Профиля',
    'Loading profile...': 'Загрузка профиля...',
    'Edit': 'Редактировать',
    'Cancel': 'Отмена',
    'Save': 'Сохранить',
    'Username': 'Имя пользователя',
    'Bio': 'Биография',
    'Your username': 'Ваше имя пользователя',
    'Add your bio': 'Добавьте свою биографию',
    'Tell us about yourself': 'Расскажите о себе',
    'Member since': 'Участник с',
    'Crypto Wallet': 'Крипто Кошелек',
    '0x... your wallet address': '0x... адрес вашего кошелька',
    'Account Settings': 'Настройки Аккаунта',
    'Account Email': 'Email Аккаунта',
    'Loading...': 'Загрузка...',
    'Private - never shown to other users': 'Приватно - никогда не показывается другим пользователям',
    'Email Notifications': 'Email Уведомления',
    'Updates about transactions and messages': 'Обновления о транзакциях и сообщениях',
    'Two-Factor Authentication': 'Двухфакторная Аутентификация',
    'Extra security for your account': 'Дополнительная безопасность для вашего аккаунта',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': 'Премиальный цифровой маркетплейс для подарочных карт, игровых аккаунтов и премиум подписок',
    'Browse Marketplace': 'Просмотреть Маркетплейс',
    'Start Selling': 'Начать Продавать',
    'Search digital items...': 'Поиск цифровых товаров...',
    'Why Choose SKID HAVEN?': 'Почему выбрать SKID HAVEN?',
    'Secure Trading': 'Безопасная Торговля',
    'Protected transactions': 'Защищенные транзакции',
    'Instant Delivery': 'Мгновенная Доставка',
    'Digital items in minutes': 'Цифровые товары за минуты',
    'Trusted Community': 'Доверенное Сообщество',
    'Verified traders': 'Проверенные трейдеры',
    'Privacy First': 'Приватность Прежде Всего',
    'Encrypted & secure': 'Зашифровано и безопасно',
    'Multiple Payments': 'Множественные Платежи',
    'Crypto, PayPal & more': 'Крипто, PayPal и другие',
    'Reputation System': 'Система Репутации',
    'Verified sellers': 'Проверенные продавцы',
    'Popular Categories': 'Популярные Категории',
    'Gift Cards': 'Подарочные Карты',
    'Game Accounts': 'Игровые Аккаунты',
    'Premium Subs': 'Премиум Подписки',
    'Digital Content': 'Цифровой Контент',
    '0 items': '0 предметов',
    'Ready to Start Trading?': 'Готовы Начать Торговать?',
    'Join our community of digital traders': 'Присоединяйтесь к нашему сообществу цифровых трейдеров',
    'Join Community': 'Присоединиться к Сообществу',
    'Start Chatting': 'Начать Общение',
    'Active Users': 'Активные Пользователи',
    'Items Sold': 'Проданные Товары',
    'Transactions': 'Транзакции',
    'Success Rate': 'Процент Успеха',
    
    // Auth
    'Login': 'Войти',
    'Sign Up': 'Регистрация',
    'Sign Out': 'Выйти',
  },
  zh: {
    // Navigation
    'Home': '首页',
    'Marketplace': '市场',
    'Sell Items': '出售商品',
    'Crypto Exchange': '加密货币交易',
    'Messages': '消息',
    'Forum': '论坛',
    'Settings': '设置',
    'Profile': '个人资料',
    'Wallet': '钱包',
    'Friends': '朋友',
    
    // Profile Hub
    'Profile Hub': '个人资料中心',
    'Loading profile...': '加载个人资料...',
    'Edit': '编辑',
    'Cancel': '取消',
    'Save': '保存',
    'Username': '用户名',
    'Bio': '个人简介',
    'Your username': '您的用户名',
    'Add your bio': '添加您的个人简介',
    'Tell us about yourself': '告诉我们关于您的信息',
    'Member since': '会员自',
    'Crypto Wallet': '加密钱包',
    '0x... your wallet address': '0x... 您的钱包地址',
    'Account Settings': '账户设置',
    'Account Email': '账户邮箱',
    'Loading...': '加载中...',
    'Private - never shown to other users': '私密 - 永远不会向其他用户显示',
    'Email Notifications': '邮件通知',
    'Updates about transactions and messages': '关于交易和消息的更新',
    'Two-Factor Authentication': '双因素认证',
    'Extra security for your account': '为您的账户提供额外安全',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': '礼品卡、游戏账户和高级订阅的首选数字市场',
    'Browse Marketplace': '浏览市场',
    'Start Selling': '开始销售',
    'Search digital items...': '搜索数字商品...',
    'Why Choose SKID HAVEN?': '为什么选择 SKID HAVEN？',
    'Secure Trading': '安全交易',
    'Protected transactions': '受保护的交易',
    'Instant Delivery': '即时交付',
    'Digital items in minutes': '数字商品分钟到账',
    'Trusted Community': '可信社区',
    'Verified traders': '已验证的交易者',
    'Privacy First': '隐私优先',
    'Encrypted & secure': '加密和安全',
    'Multiple Payments': '多种支付方式',
    'Crypto, PayPal & more': '加密货币、PayPal 等',
    'Reputation System': '声誉系统',
    'Verified sellers': '已验证的卖家',
    'Popular Categories': '热门类别',
    'Gift Cards': '礼品卡',
    'Game Accounts': '游戏账户',
    'Premium Subs': '高级订阅',
    'Digital Content': '数字内容',
    '0 items': '0 件商品',
    'Ready to Start Trading?': '准备开始交易？',
    'Join our community of digital traders': '加入我们的数字交易者社区',
    'Join Community': '加入社区',
    'Start Chatting': '开始聊天',
    'Active Users': '活跃用户',
    'Items Sold': '已售商品',
    'Transactions': '交易',
    'Success Rate': '成功率',
    
    // Auth
    'Login': '登录',
    'Sign Up': '注册',
    'Sign Out': '退出',
  },
  ja: {
    // Navigation
    'Home': 'ホーム',
    'Marketplace': 'マーケットプレイス',
    'Sell Items': '商品を売る',
    'Crypto Exchange': '暗号通貨取引',
    'Messages': 'メッセージ',
    'Forum': 'フォーラム',
    'Settings': '設定',
    'Profile': 'プロフィール',
    'Wallet': 'ウォレット',
    'Friends': '友達',
    
    // Profile Hub
    'Profile Hub': 'プロフィールハブ',
    'Loading profile...': 'プロフィールを読み込み中...',
    'Edit': '編集',
    'Cancel': 'キャンセル',
    'Save': '保存',
    'Username': 'ユーザー名',
    'Bio': '自己紹介',
    'Your username': 'あなたのユーザー名',
    'Add your bio': '自己紹介を追加',
    'Tell us about yourself': 'あなたについて教えてください',
    'Member since': 'メンバー歴',
    'Crypto Wallet': '暗号ウォレット',
    '0x... your wallet address': '0x... あなたのウォレットアドレス',
    'Account Settings': 'アカウント設定',
    'Account Email': 'アカウントメール',
    'Loading...': '読み込み中...',
    'Private - never shown to other users': 'プライベート - 他のユーザーには表示されません',
    'Email Notifications': 'メール通知',
    'Updates about transactions and messages': '取引とメッセージについての更新',
    'Two-Factor Authentication': '二要素認証',
    'Extra security for your account': 'アカウントの追加セキュリティ',
    
    // Home Page
    'The premier digital marketplace for gift cards, game accounts, and premium subscriptions': 'ギフトカード、ゲームアカウント、プレミアムサブスクリプションの最高のデジタルマーケットプレイス',
    'Browse Marketplace': 'マーケットプレイスを閲覧',
    'Start Selling': '販売を開始',
    'Search digital items...': 'デジタルアイテムを検索...',
    'Why Choose SKID HAVEN?': 'なぜSKID HAVENを選ぶのか？',
    'Secure Trading': '安全な取引',
    'Protected transactions': '保護された取引',
    'Instant Delivery': '即座の配送',
    'Digital items in minutes': '数分でデジタルアイテム',
    'Trusted Community': '信頼できるコミュニティ',
    'Verified traders': '認証済みトレーダー',
    'Privacy First': 'プライバシー優先',
    'Encrypted & secure': '暗号化と安全',
    'Multiple Payments': '複数の支払い',
    'Crypto, PayPal & more': '暗号通貨、PayPalなど',
    'Reputation System': '評判システム',
    'Verified sellers': '認証済みセラー',
    'Popular Categories': '人気カテゴリー',
    'Gift Cards': 'ギフトカード',
    'Game Accounts': 'ゲームアカウント',
    'Premium Subs': 'プレミアムサブスク',
    'Digital Content': 'デジタルコンテンツ',
    '0 items': '0アイテム',
    'Ready to Start Trading?': '取引を始める準備はできましたか？',
    'Join our community of digital traders': 'デジタルトレーダーのコミュニティに参加',
    'Join Community': 'コミュニティに参加',
    'Start Chatting': 'チャットを開始',
    'Active Users': 'アクティブユーザー',
    'Items Sold': '販売済みアイテム',
    'Transactions': '取引',
    'Success Rate': '成功率',
    
    // Auth
    'Login': 'ログイン',
    'Sign Up': 'サインアップ',
    'Sign Out': 'サインアウト',
  },
};

const translate = (key: string, currentLanguage: string): string => {
  return translations[currentLanguage]?.[key] || key;
};

export const useLanguage = () => {
  const [currentLanguage, setCurrentLanguage] = useState<string>('en');
  const { toast } = useToast();

  useEffect(() => {
    const savedLanguage = localStorage.getItem('kid-haven-language');
    if (savedLanguage && languages.find(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (languageCode: string) => {
    const language = languages.find(lang => lang.code === languageCode);
    if (language) {
      setCurrentLanguage(languageCode);
      localStorage.setItem('kid-haven-language', languageCode);
      
      toast({
        title: "Language Changed! 🌍",
        description: `Switched to ${language.name}`,
      });
      
      console.log('Language changed to:', language.name);
      
      // Force re-render by triggering a custom event
      window.dispatchEvent(new CustomEvent('languageChanged', { detail: languageCode }));
      
      return true;
    }
    return false;
  };

  const getCurrentLanguage = () => {
    return languages.find(lang => lang.code === currentLanguage) || languages[0];
  };

  const t = (key: string) => translate(key, currentLanguage);

  return {
    currentLanguage,
    changeLanguage,
    getCurrentLanguage,
    availableLanguages: languages,
    t
  };
};
