// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clxadihpaoewelomyjqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNseGFkaWhwYW9ld2Vsb215anFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTQxMzksImV4cCI6MjA2Njc3MDEzOX0.PXAkbEFdS9XwzH0rta4AmnqdkcTCH55WkRyHiK_KX2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);