// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whytdturynbsiuyntnuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoeXRkdHVyeW5ic2l1eW50bnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDExNDgsImV4cCI6MjA2MTcxNzE0OH0.eWMTpjqcaV9WnreDrOgS4wUuMWfnWaVJI2mn89hScIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);